### ISSUE TITLE
Demo Server Registration Is Down?

### ISSUE THREAD

**Issue by LukeSchoen** [boringproxy/boringproxy#104]
I love using the demo server! (it's super fast and simple for making small tests that run across the internet)

Alas, when I tried making a new account today

(in the section: "If you submit your email address using the form below, it will create an account for you and send you a login link so you can create tunnels.")

I got:

Post "http://localhost:44221/request": EOF

And no email was sent, I know the demo server is not your top priority but if this is a small fix I would really appreciate it!

Keep up the excellent work my man! when BP and or demo server is working it is an absolutely glorious service!

Best Regards

**Comment by anderspitman** [comment]
Hey @LukeSchoen, I took down the demo server because I noticed the domain had been flagged. This indicates that people are using it for spam and/or phishing attacks, etc. This happens with basically any free service. Sadly I don't have the resources to properly handle this, so currently self-hosting is the only way to use boringproxy. I'd recommend using Cloudflare Tunnel if you need a free tunneling service.
