### ISSUE TITLE
Allow changing webserver bind port

### ISSUE THREAD

**Issue by tazz4843** [boringproxy/boringproxy#105]
boringproxy is by far the easiest and best reverse proxy solution I've found. I'd like to be able to use the server it's hosted on for other things though, and considering it binds to port 80/443 that makes it quite difficult to do so.
If possible I'd love a flag to disable binding https and change the port that http binds on, or even better (although I'd assume much more difficult) a option to serve the http server over Unix Domain Socket.
Thanks for making this!

**Comment by anderspitman** [comment]
Hey @tazz4843, glad boringproxy is useful for you.

Use of TLS is deeply integrated into the design of boringproxy. Can you share the use case you're trying to accomplish?

**Comment by mohanadkaleia** [comment]
Heavy + on this request, I also love to give the option to change the binding port to be used, for example I have a server where I'm hosting some projects and I'm using nginx as a reverse proxy which is running on port 80. 

On the same time I'd like to use the same server with boringproxy to point into my local dev server, but since the port 80 is already taken by nginx I can't run boringproxy directly. 

Ideally would love to use port 8081 fpr example to bind boringproxy with instead of port 80.

Thank you!

**Comment by tazz4843** [comment]
Disabling HTTPS wouldn't be a requirement by any means, since reverse proxying 80 *and* 443 is still easy. My use case would be almost exactly the same as mohanadkaleia's above, putting it behind nginx and using it as a reverse proxy.

**Comment by mohanadkaleia** [comment]
I think here is where the listening to port 80 is taking place <[code](https://github.com/boringproxy/boringproxy/blob/e4b6598274fc34ab028b733e090fb5a00f350bb3/boringproxy.go#L148)>

I wonder if we can add an extra parameter to the command to set the port that it is listening to (we can set it to 80 by default)

**Comment by anderspitman** [comment]
Ok so you don't want to run boringproxy *behind* nginx, just side-by-side, where nginx handles HTTP requests on port 80 and boringproxy handles HTTPS requests on port 443? That should be doable. As @mohanadkaleia points out I would just need to add parameters for choosing the HTTP and HTTPS ports.

This raises another question though: why are you running any traffic over HTTP? I'd recommend either setting up nginx to use LetsEncrypt or dropping nginx and using something like boringproxy or Caddy (if you need more reverse proxy features) which integrates HTTPS automatically.

**Comment by anderspitman** [comment]
In that case do you have nginx configured to pass-through TLS (ie nginx acting as an SNI proxy)? If not, that's where it would require significant changes to boringproxy in order to work in this case. boringproxy is designed with simplicity as a central tenet. You can't always avoid complexity, but when it gets to the point where you're trying to set up 2 layers of reverse proxies, I think it's worth taking a step back and seeing if you can achieve your goals with a simpler setup.

**Comment by tazz4843** [comment]
That's a fair point. Rethinking it, putting it *behind* nginx wouldn't be a requirement, as long as ports 80/443 could both be changed, running alongside would be fine.

**Comment by anderspitman** [comment]
See also #42

**Comment by anderspitman** [comment]
This should be working in the latest release, using `-http-port`, `-https-port`, and `-allow-http`.
