### ISSUE TITLE
SSL error from https://demo-signup.boringproxy.io/request

### ISSUE THREAD

**Issue by pmorch** [boringproxy/boringproxy#119]
Tried with both Firefox and Chrome and on both Windows inside a restrictive firewall and on my own home Linux box with just NAT.

When I tried to enter my email address in the signup form on https://boringproxy.io/, I'm shown this in Firefox:

![image](https://user-images.githubusercontent.com/159292/147165355-e3fb5ffe-cf3e-4388-b9a1-a8b0dafd80be.png)

If you've read this far, I'd like to know if `boringproxy` needs to contact other ports than 443 (and perhaps 80) on the "central" server. Our corporate firewall restricts *all* outgoing requests that aren't to one of those two ports. I guess admins will need to know what firewall rules to allow. I'm guessing that access to port 22 is required too though, huh?

**Comment by anderspitman** [comment]
Hey @pmorch. I had shut down the demo site for a while since I was concerned about abuse, but I just started it back up since I'm not sure it was actually a problem.

You are correct that port 22 is required for outgoing, unfortunately. Eventually I'd like to implement a tunneling scheme that can all be done over 443, but that probably won't be for quite a while. If you can't get IT to allow 22, I could add an option to the server to let you configure the SSH port, then you could run your SSH server on port 80 while setting `-http-port` to something else. It would break 80->443 redirects for HTTP, but should work for tunneling.

**Comment by pmorch** [comment]
@anderspitman, I can confirm that there no longer are any SSL problems.

I can't get IT to allow 22 - trust me, I've tried. About the option to let me configure the SSH port, that would be required for both client and server, I'm guessing. And while that would definitely solve our our use case, do it when and if it makes sense for you. If I could ask something it would be that you document the required ports, 22, 80 and 443 for the time being.

Also, just FYI, now that SSL is working I was sent a link to https://bpdemo.brng.pro/login?access_token=XXXX. When I visited that, I was shown:

![image](https://user-images.githubusercontent.com/159292/147211867-773616ac-fd97-4d43-8b82-2d1e0aaba098.png)

The "please click here" link was to http://url.fortinet.net/rate/submit.php?id=XXXX&cat=3D&loc=https://bpdemo%2ebrng%2epro%2f&ver=8 (I'm happy to send you the full link directly if you write to me at peter@morch.com)

So for some reason, you're not friends with Fortinet's firewall. Which is strange, because it doesn't object to https://ngrok.com/.

**Comment by anderspitman** [comment]
Thanks @pmorch. I'm not familiar with Fortinet. Is that part of your home ISP, your work setup, or something else?

I probably won't change the default port on the demo server, since it's just for trying out boringproxy and not meant as a free tunneling service. But if you decide to self-host on a VPS I'm happy to help you get it working.

**Comment by anderspitman** [comment]
I opened #121 to track improving the docs for required ports.

**Comment by pmorch** [comment]
It is our company's IT department that uses a Fortinet firewall. (I think it is a whole suite of things, including a VPN solution). It blocks certain URLs, it blocks everything outgoing except ports 80 and 443, it contains a virus scanner, and likely more that I haven't yet discovered.

**Comment by anderspitman** [comment]
Gotcha, thanks!
