### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by quite** [boringproxy/boringproxy#16]
Relevant read https://www.nginx.com/blog/websocket-nginx/

**Comment by anderspitman** [comment]
This is very much on the near-future roadmap! It's unfortunate that so many services use WebSockets when HTTP/2 + server sent events would handle their needs, because WS requires a significantly different code path. But it's so popular I don't think there's any avoiding it.

**Comment by anderspitman** [comment]
Hey @oufly, sorry for the late response. I haven't made much time to work on boringproxy recently. Is there some specific reason you can't use a more production-quality solution like ngrok or Cloudflare Tunnel (this is what I recommend to most people).

**Comment by asm0dey** [comment]
@anderspitman, for me, the reason is: I don't need a production-level proxy; I need a simple thing to install and use on my own server even without domain specified.

**Comment by deviantintegral** [comment]
I originally wanted to use boringproxy to access Home Assistant, but it's UI uses websockets. I ended up using Nabu Casa cloud (run by the HA team) and it's been great. I imagine there are other self-hosted apps with decoupled frontends that use websockets as well.

**Comment by 3crow** [comment]
>use boringproxy to access Home Assistant

Myself also.
Loving borignproxy so far, Blue iris and Jellyfin both running on it. Went to add HA and ended up here.
Thanks to black friday, my VPS is costing less than Naba Casa. Using my own VPS means I can do lots of stuff on my own real estate rather than buying many various cheap services that add up to a fair bit.

I have 2 personal location, my home and mothers home both getting internet from mobile networks. I don't like the idea of VPN's to the VPS in case the VPS is hacked. Boring proxy seems a great way to access the many systems I have running in a relatively secure way- any services accessed will need a password locally.

**Comment by anderspitman** [comment]
Hey all just wanted to chime in and say I've made more time for boringproxy lately. I don't know when I'll have time to dig into it, but I think websocket support has a high likelihood of being added eventually.

**Comment by chernesk** [comment]
Is there anything that I can do to help this become a reality? I'm glad to help with code if you point me in the right direction. I'm also glad, within reason, to help financially.

This feature would be a great addition to my workflow.

**Comment by anderspitman** [comment]
Thanks for offering @chernesk. I'm currently prepping for the next release of boringproxy. This one's going to be huge and I'm really excited about it. So I probably won't have time to look into websockets support until after that, so at least a week or two out.

If someone is really bored, there may be a workaround worth trying. If the upstream service (ie Home Assistant) supports the ACME (ie LetsEncrypt) HTTP-01 and/or TLS-ALPN-01 challenge types, I believe setting the boringproxy tunnel TLS Termination to Passthrough *might* work. So basically Home Assistant would be managing its own certs, rather than having the boringproxy server (Server TLS Termination) or client (Client TLS Termination) do it. This is untested and likely to have issues. For example, most programs that include LetsEncrypt support require that you run them on ports 80/443, because those are the only ports LetsEncrypt supports, even though this isn't actually necessary if boringproxy is tunneling the traffic.

If you really want to dig into the code, which unfortunately isn't the cleanest I've ever written, I *believe* what needs to happen is somewhere around here:

https://github.com/boringproxy/boringproxy/blob/ec6739ea63e8b6616a65c38c0de0cd84c7d994eb/http_proxy.go#L70

You need to detect that the request is a WebSocket upgrade then do 3 things:

1. Hijack the request socket (https://pkg.go.dev/net/http#Hijacker) to gain control of the underlying TCP connection.
2. When we make the upstream request, we also need to hijack that. I'm not sure if you can do that directly in Golang, or if we need to use a library (this looks promising: https://stackoverflow.com/questions/23812330/go-hijack-client-connection).
3. Connect the first two parts together, similar to what you see here: https://github.com/boringproxy/boringproxy/blob/ec6739ea63e8b6616a65c38c0de0cd84c7d994eb/boringproxy.go#L331

There may be more too it than that, but at the end of the day it may not be that difficult for me to do it.

**Comment by anderspitman** [comment]
Ah yes I'm remembering the reason it requires this special dance is because WebSockets use "hop-by-hop" headers, which means we have to manually forward the request:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism

**Comment by chernesk** [comment]
I'll try the passthrough method and see if that works. If not, I'll take a look at the code to see if I can help (I'm a Java and Ruby developer, so not a seasoned go developer (yet). 

My use cases are a work app that I'd really like to be able to use through this mechanism and another personally hosted app  (Tandoor Recipes).

Again, glad to help and/or help test. Looking forward to the big release and absoutely love the app. Thanks for all of the time that you've taken creating it!

**Comment by anderspitman** [comment]
Sounds good. Let me know how it goes. Thanks @chernesk!

**Comment by 3crow** [comment]
I had tried this before and not got it working - found this via google and gave up.

Anyhow was messing with it again yesterday and couldn't get it working. I'd left tunnel open overnight and by accident connect ed this morning and it worked great.
Using passthrough and the network ip rather than localhost

**Comment by anderspitman** [comment]
Hey all, it occurred to me that maybe I was overthinking WebSocket support. Rather than implementing a proper hop-by-hop WS proxy in boringproxy, why not just implement raw TLS tunnels and let the upstream server handle the WS upgrade? This has the added huge benefit of supporting any TLS protocol. I've hacked together a basic prototype. Would one of you be willing to test with Home Assistant to verify WebSockets are working with the build here:

https://gemdrive.io/apps/delver/?drive=https://files.apitman.com&path=/public/boringproxy/raw-tls

Thanks!

**Comment by chernesk** [comment]
I will try to test this tonight or over the weekend.

Really appreciate it!

**Comment by anderspitman** [comment]
Awesome, thanks! If it works this would definitely be a win-win. boringproxy stays simpler, while adding support for WS and other protocols.

**Comment by chernesk** [comment]
Trying to download. Getting unauthorized.

**Comment by anderspitman** [comment]
Weird. I'm on the road. Does this direct link work?

https://files.apitman.com/public/boringproxy/raw-tls/boringproxy-linux-x86_64

**Comment by anderspitman** [comment]
Let me know if you need a different architecture.

**Comment by anderspitman** [comment]
Oh if you tried the "Open in Tab" button that won't work. Try the Download button or copy the link directly

**Comment by anderspitman** [comment]
@chernesk I went ahead and merged the branch into master, and will include it in the next release. I'm fairly confident it works, or at least shouldn't break anything. I'll leave this open until that release comes out and we also know for sure that Home Assistant is working.

**Comment by WGrobler** [comment]
@anderspitman, I did some quick tests this afternoon. Seems to be working on HA. I'll do some proper tests and give feedback. 

Since this is passing TSL to Client, I assume boringproxy is not generating certificates for the domains? We will have to generate certificates on the client server and add it to Home Assistant to allow HTTPS access?

**Comment by anderspitman** [comment]
> @anderspitman, I did some quick tests this afternoon. Seems to be working on HA. I'll do some proper tests and give feedback.

Awesome, thanks @WGrobler.

> Since this is passing TSL to Client, I assume boringproxy is not generating certificates for the domains? We will have to generate certificates on the client server and add it to Home Assistant to allow HTTPS access?

Nope! The boringproxy client takes care of getting the certs and unwrapping it so HA only has to worry about handling the raw TCP, which in this case is a HTTP/1.1 Upgrade request for WebSockets.

**Comment by chernesk** [comment]
Thanks @WGrobler. Life often gets in the way for me. Sorry that I haven't been more help.

This is great news! Thank you so much @WGrobler for testing and @anderspitman for the coding! I think that I actually have a little bit of time right now, so I'll check out my other use cases.

**Comment by WGrobler** [comment]
I did some more testing. New certificates did not generate on my system, apparently I triggered a rate limiter at Let's Encrypt. Therefore, I can't test certificate generation at this time. Looking at the code, it should work as before. 

Using an existing certificate I managed to set up a new instance of Home Assistant over HTTPS. 

I'm busy working on a docker branch that included docker-compose files for server & client setups including a home assistant example. It still requires documentation before I can create a pull request, but the files are available on my fork [github.com/WGrobler/boringproxy/tree/docker-files-for-usage](https://github.com/WGrobler/boringproxy/tree/docker-files-for-usage)
Current docker-compose files pull images from my git container packages, but we can change that to the primary repo.

**Comment by chernesk** [comment]
That's awesome about the docker work. I'll be using that as well!

**Comment by matbgn** [comment]
Hi folks, 

What an amazing journey till there. So impressive to see you all pushing hard to solve this issue.

If I could add my small contribution, I would mention [Cryptpad](https://github.com/xwiki-labs/cryptpad) as a really powerfull diagnostic app for header policy forwarding and so on with its https://domain.xyz/checkup page.

Cryptpad uses websocket and thanks to your last RAW_TLS package I achieved to deploy it with https certs. The installation itself is based on two separate urls, one main domain and one sandbox for XSS security purpose.

What remains are those warnings, maybe you could fix some of those (sorry my know-how in field of TLS is really limited):
[https___cryptpad_checkup_.pdf](https://github.com/boringproxy/boringproxy/files/8088183/https___cryptpad_checkup_.pdf)

Hope this brings some inshights for further developpement.

And last but not least many thanks for your incredible work @anderspitman :heart:

**Comment by anderspitman** [comment]
I agree this type of conformance testing is a great idea. @matbgn please open another issue so we can focus more directly on that.

Also https://domain.xyz/checkup appears to be down.

**Comment by almereyda** [comment]
> Also https://domain.xyz/checkup appears to be down.

This is a page that is intended for use by authenticated CryptPad administrators and might have been an example domain, such as `example.com`, but a little funkyer ^_^ I suspect this domain does not actually exist.

**Comment by anderspitman** [comment]
Ah ok that makes sense.

**Comment by matbgn** [comment]
> > Also https://domain.xyz/checkup appears to be down.
> 
> This is a page that is intended for use by authenticated CryptPad administrators and might have been an example domain, such as `example.com`, but a little funkyer ^_^ I suspect this domain does not actually exist.

Totally right sorry for the funky `example.com` :smile: 

Just a small note to second @WGrobler, new certificates do not generate client system when using client TLS. @anderspitman do you have any recommandation to generate it manually the efficient way?

**Comment by anderspitman** [comment]
> Totally right sorry for the funky `example.com` smile

No worries. It's pretty obvious in hindsight haha.

> Just a small note to second @WGrobler, new certificates do not generate on client system when using client TLS.

Yeah this looks like a bug with the Client TLS code. Should be an easy fix. I'm in the middle of making some other changes so I'll open an issue to track that.

**Comment by anderspitman** [comment]
https://github.com/boringproxy/boringproxy/issues/145

**Comment by matbgn** [comment]
Many thanks could you push linux arm64 and linux x86_64 packages on https://gemdrive.io/apps/delver/?drive=https://files.apitman.com&path=/public/boringproxy/raw-tls ?

**Comment by anderspitman** [comment]
@matbgn since there are now multiple changes on master, use this link:

https://gemdrive.io/apps/delver/?drive=https://files.apitman.com&path=/public/boringproxy/master

**Comment by anderspitman** [comment]
Fixed in v0.9.0!
