### ISSUE TITLE
REST API And Database

### ISSUE THREAD

**Issue by vqoley** [boringproxy/boringproxy#188]
Im looking for people can show me rest api url for curl, not source code also if developer can adjust code to create database for mysql because i want help do php administrator and user UI with by connecting API to mysql database. Im sorry i request this because i still new in python also doesn't anything about golang. I only expert in PHP, CSS, HTML and MYSQL and little JS.

**Comment by almereyda** [comment]
This feels very off topic to Boring Proxy. Please try to find help in other online spaces dedicated to skill sharing, like StackOverflow. Good luck!

**Comment by vqoley** [comment]
> This feels very off topic to Boring Proxy. Please try to find help in other online spaces dedicated to skill sharing, like StackOverflow. Good luck!

I don't think you understand my question. I not mention boringproxy on there not meaning its off topic. Why should i go stackoverflow? What i request is REST api (not source) from this project. Because i want help/support this project by creating full admin and client web UI. Its like user can register, reset password, notification, telegram bot and more based of this API. About database it will convert database json to mysql meaning its useful to handle big data.

**Comment by anderspitman** [comment]
Hey @vqoley, I understand your request better now. Unfortunately, while boringproxy does have a programmable API, it's not currently encouraged for other developers to use it, since it is unstable and may change a lot. Also, there's no documentation for it.

I think boringproxy probably is too immature of a project for what you're trying to accomplish. I'd recommend trying to find something that's past version 1.0 with a stable API.

Let me know if you have any more questions.
