### ISSUE TITLE
Feature Request: Client Download

### ISSUE THREAD

**Issue by explorigin** [boringproxy/boringproxy#19]
When setting up the server, add a feature where you can register a set of clients that can be downloaded. This will ease setting up clients since you won't have to setup some other transmission medium. It will be helpful to register multiple binaries since a client could have a different architecture than the server.

**Comment by anderspitman** [comment]
Hey @explorigin,

I thought about doing this initially, but decided against it, mostly because the deployment for the server and client is almost the same process (they even share the same executable if you're on the same architecture). So I don't imagine a lot of scenarios where you can download the server from GitHub but can't download the client at the same time. It also adds significant complexity for the server deployment, as you now need more than just the executable.

Can you explain your use case more and how you ran into this as a problem?

**Comment by explorigin** [comment]
x64 server in the cloud, Raspberry Pi at home. I didn't want the whole go toolchain on the pi so I just cross-compiled on the server.

**Comment by anderspitman** [comment]
Is there a reason you couldn't download the ARM build directly, ie: 

https://github.com/boringproxy/boringproxy/releases/download/v0.3.0/boringproxy-linux-arm

Same question for x64, actually.

**Comment by explorigin** [comment]
That's my fault I guess. I saw the docs on Building and (since it wasn't mentioned) didn't check for release binaries.

**Comment by anderspitman** [comment]
No that's fair. I'm guessing you were linked directly to the GitHub repo and not the website (boringproxy.io)? The repo is pretty sparse on info other than for building from source.

**Comment by anderspitman** [comment]
I added a note to the top of the README pointing people to the website first.
