### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by pentagon98** [boringproxy/boringproxy#21]
Hi,

first of all, thank you for this project, it is exactly what I was looking for.
Second, if this isn't the place for this issue, please just say so, and I'll close it.

My problem essentially is: I have installed the boringproxy server on my server, and I created a tunnel for my CyberChef container.
I went to my admin interface, and created a tunnel. 

![1](https://user-images.githubusercontent.com/10035715/101082566-ef92ff00-35ab-11eb-998d-9be84c90ae7e.png)

Zoe2 is the client running on the same server as my boringproxy server.

However, when I tried to open the tunnel, I got this:

![1](https://user-images.githubusercontent.com/10035715/101090927-b3659b80-35b7-11eb-9ab1-41b36533ddfb.png)

I use cloudflare, however I have set to DNS entries to DNS only, so they are not being proxyied through cloudflare.
My DNS entries are for *.mydomain.com, mydomain.com and www.mydomain.com.
Cloudflare's automatic SSL is turned off.
Cyberchef is running in Docker, with its port on port 9010.

**Comment by anderspitman** [comment]
Hey @pentagon98, thanks for giving boringproxy a try. Hopefully we can get this figured out for you.

A couple things first off:

1. The error messages obviously need to be improved. Basically the error you're seeing means the boringproxy server isn't able to connect to the SSH tunnel port.

2. Based on the UI, it looks like you're not using the latest version (v0.4.0). It will be easier to debug if you can use that version.

My best guess is that there's some issue with the server and client running on the same machine. I haven't tested this configuration very much, since typically if you can run your services on the same machine, you could just use a normal reverse proxy like Caddy or nginx. Just to confirm, do you have OpenSSH server version 7.7+ running and you're able to ssh into the machine?

**Comment by anderspitman** [comment]
As a side note, I've considered adding a feature to the server to let you specify the tunnel port yourself, rather than a random one being chosen. This would let you choose port 9010, and completely bypass the need for running the client at all. Essentially this lets boringproxy run as a normal reverse proxy (albeit a simple one).

Would this be useful for you long-term, or are you just running them on the same machine for testing and eventually planning to run the client on a separate machine (ie behind a NAT or something)?

**Comment by pentagon98** [comment]
Hell @anderspitman,

thank you for the fast reply!
I'm running OpenSSH_8.2p1 on Ubuntu Server.
I'm port forwarding ports 80 and 443, but I'm not forwarding 22.

I downloaded v0.4.0., here are the screenshots:

![1](https://user-images.githubusercontent.com/10035715/101086727-9201b100-35b1-11eb-8f55-301b078f78f1.png)

![2](https://user-images.githubusercontent.com/10035715/101086742-962dce80-35b1-11eb-9e32-f2777da7e822.png)

I also tried it on a different machine (separate server and client) and after a few minutes, it worked.
So the problem was probably in trying to run it on the same machine.

Currently I'm just testing things, as my home router (for some reason) always crashes without cloudflare proxy.
But if it didn't, I thing I would use boringproxy, as setting it up is much easier than Nginx or trafik.

**Comment by anderspitman** [comment]
Before I respond I wanted to point out that you're domain is visible in the screenshot (on the tab), even though you're trying to obscure it. You might want to delete or replace those screenshots...

**Comment by anderspitman** [comment]
Ok as suspected I think there may be a bug when running on the same machine. If I understand correctly the server is running on your home network, correct? Are you logged into it directly, or accessing it over SSH on your local network?

If port 22 isn't forwarded that will likely break it, because the client is going to use the admin-domain (ie cyberchef.*.com) for accessing the SSH server. I'm surprised it worked when you switched to different machines though, as there's isn't currently a way to tell the client to use an alternative address for accessing the SSH server, which means it needs to be able to access it with the public address.

**Comment by pentagon98** [comment]
It is running on my home network, yes, and I'm accessing it over SSH.
When I tried it with the second machine, I port forwarded port 22, so that's why it probably worked.
I should have added that to my comment, sorry.

Unfortunately, my domain is still visible in the edit history.
Would you mind terribly if I deleted my comments after this issue is closed?

As far as I see, my problem was that both the server and client are running on the same machine (which isn't how it's supposed to be set up anyways) and port 22 was closed.

**Comment by anderspitman** [comment]
Yeah no worries feel free to delete them.

Would you mind trying them on the same machine again, now that port 22 is forwarded? I think it should work.

Failing that, another thing you can do is look at the web UI to figure out what port got randomly assigned to the tunnel, then tell your docker container to use that port instead of 9010. I'm using this hack myself for one of my instances.

**Comment by pentagon98** [comment]
@anderspitman  thank you, with 22 forwarded, it works perfectly.
Thanks for being helpful and for writing this awesome piece of software!

**Comment by anderspitman** [comment]
Excellent; glad it worked!
