### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#33]
I leave one of my services using boringproxy and it went offline (9 hrs) overnight because of broken pipe.

![image](https://user-images.githubusercontent.com/60437695/104125799-07029c00-5351-11eb-9377-85254ca76393.png)

**Comment by voarsh2** [comment]
There was no automatic reconnect/handling of this.

**Comment by voarsh2** [comment]
After I turned off the server version to increase limits, the client stopped working and when I turned the server back on, the client didn't connect automatically again. https://github.com/boringproxy/boringproxy/issues/34#issuecomment-757496422

**Comment by voarsh2** [comment]
I have zero idea why I must constantly restart the client, I one http error I receive is
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Every 10-15 minutes on a site with many requests the client just stops working. No errors, no console output, I just have to restart it.

**Comment by voarsh2** [comment]
I would expect something like this from boringproxy:
![image](https://user-images.githubusercontent.com/60437695/104199163-fe789700-541e-11eb-91ca-490351c068c4.png)

**Comment by anderspitman** [comment]
Yeah the auto-reconnect functionality is currently very limited. The biggest problem I've run into is sometimes if the client crashes, the server doesn't close its side of the SSH tunnels, and the client can't reconnect. Only solution I've found so far is to `killall sshd` on the server, which is quite annoying. However, this has been much less of an issue since the client is more stable and hasn't crashed for me in a long time.

**Comment by voarsh2** [comment]
I tested the client on a site that gets thousands of requests to specific files and hundreds of visitors a day and the client just freezes/dies.

Is there anything I can give you to help workout why this happens? Or do you know why and need time/contribution to fixing it?
________________________________

**Comment by anderspitman** [comment]
You'll probably need a developer with access to the site and the boringproxy code to debug something like this. I haven't had any similar issues since the very early versions. It's probably either a load problem (the machine running the client isn't powerful enough) or boringproxy has a memory leak or similar. Easiest thing to start with is monitoring your memory usage to see what's happening there.

If you share your tunnel settings that might give more insight but unlikely.

**Comment by anderspitman** [comment]
Also check your CPU usage.

**Comment by anderspitman** [comment]
I belive this may be fixed by setting the `ClientAliveInterval` on your SSH server. See here:

https://github.com/boringproxy/boringproxy/issues/23#issuecomment-766160657
