### ISSUE TITLE
Failed to get cert error

### ISSUE THREAD

**Issue by whitetigle** [boringproxy/boringproxy#37]
Hi! 
Newbie here. 

I just installed boringproxy on a new linux box running nginx. I updated the sshd (GatewayPorts) config and restarted the sshd service. I launched the client and got the `SyncTunnels ` log output.

On the server I can see the linux box but when I want to add tunnel from the web admin I get a `Failed to get cert` error.
Any things I forgot about the setup?

Thanks in advance for your help and for working on this awesome project.

**Comment by anderspitman** [comment]
Hi @whitetigle,

That error usually means that the boringproxy server isn't running on the public internet, or it's not running on ports 80/443.

That said, I'm not sure I have a clear image of your setup. Normally with boringproxy you'll have at least 2 different machines running, one with the boringproxy server, one (or several) with the client. The server machine is on the public internet, and often the clients are behind NAT or similar. Only the server needs sshd running. Also, usually you wouldn't need nginx because it's a reverse proxy and boringproxy would fill that role.

Can you explain how your setup lines up with all these roles? Thanks!

**Comment by whitetigle** [comment]
Hi @anderspitman and thanks for taking time to answer.

I do have a boringproxy server which works like a charm with several clients (RPIs). 😃 

In fact I was just trying to see to what extent I could use boringproxy since it's convenient to create/delete subdomains at will. So I guess already having a reverse proxy with certbot is a problem? Anyway I don't want you to lose time on this if that's complicated. 

Again thanks for the good work on the project!

**Comment by anderspitman** [comment]
Well the main problem right now is that combining boringproxy with other reverse proxies is untested, because it's not a need I have. boringproxy definitely won't work *behind* nginx if nginx is handling Let's Encrypt ACME certs. There's a chance nginx would work behind boringproxy, but like I said that's untested.

Other than the fact that it's still in beta and missing some important features (auto gzip for example), is there a reason you wouldn't want to replace nginx with boringproxy?

**Comment by whitetigle** [comment]
For 90% of my needs, Nginx acts as a reverse proxy, so boringproxy could absolutely play this role.
The only reason I see now is that Nginx has been battle tested for years and there's a large team working on the product.
However, I am an early adopter and I'm usually ok to take risks and see how, paradoxically, that could make my life easier.
Often it has allowed me to move faster on niche projects.

So I could totally replace nginx with boringproxy and see how that turns. 👍

**Comment by anderspitman** [comment]
Personally I'd probably recommend you at least wait for 1.0. I'd hate for you to have it fail at a bad time and leave a bad impression. But of course if you choose otherwise I appreciate the beta testing.

**Comment by anderspitman** [comment]
I'm going to close this in favor of #38. Feel free to comment here if something changes and you think there's a different cause to the errors you're seeing.
