### ISSUE TITLE
Ensure it works in front of and behind other reverse proxies

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#38]

**Comment by matejdro** [comment]
I want to use boringproxy as a ngrok alternative (so I can quickly create world-accessible server for development purposes). My setup is currently:

World <HTTPS> Nginx <HTTP> BoringProxy

I want Nginx to handle all certificate and encryption stuff, I just want boringproxy to tunnel the websites for me.

From my testing, this is currently not possible (starting server fails because it can't get the certificate). Is this use case that boringproxy covers or should I look for a different alternative?

Thanks.

**Comment by anderspitman** [comment]
Hi @matejdro,

You are correct that this won't currently work, because boringproxy is HTTPS-only and expects to manage the certs itself. Adding support for HTTP is something I'm willing to consider. I believe this would make it easier to work behind CDNs like CloudFlare, which would be a great feature.

Just to make sure I understand what you're proposing, you would have a wildcard server block in your nginx config like `*.example.com` which would point everything on those subdomains to your boringproxy upstream server, and you want boringproxy to use the `X-Forwarded-Host` header to determine which tunnel to proxy the request to?

**Comment by matejdro** [comment]
I have my domain `example.com` and I have various services running under various subdomains (`X.example.com`). 

My idea is that I would allocate a subdomain (for example `bp.example.com`) to the boring proxy via nginx (through `X-Forwarded-Host` like you mentioned) and then boring proxy would create sub-sub-domains (`X.bp.example.com`) for any development services that I would route through it.

**Comment by anderspitman** [comment]
Ok yeah that would work assuming I implement HTTP support at some point.

As a workaround for now could you disable TLS for *.bp.example.com and just pass it through? Not sure if nginx can do that or not.

**Comment by matejdro** [comment]
It looks like it is possible to pass TLS though with nginx but it is a bit more complicated (I would have to install special nginx version that has `ngx_stream_ssl_preread_module`) and I would have to have certificate management split into two (I like having things neatly in once place). But I'm not in a rush, so I don't mind waiting until this is properly possible. Thanks.

**Comment by anderspitman** [comment]
Sounds good. I've added issue #42 specifically to track this.

**Comment by almereyda** [comment]
Assuming this issue here is the one announced in https://github.com/boringproxy/boringproxy/issues/8#issuecomment-722528521 to add more regular reverse proxy headers, and assuming we can switch operation modes at times, the contexts of https://github.com/boringproxy/boringproxy/issues/42#issuecomment-774915567 and https://github.com/boringproxy/boringproxy/issues/35#issuecomment-758091437 allow to foresee more situations in which third-party applications will want to reuse certificates created by the `client`, may it be useful to consider sending SIGHUP signals to certain processes after certificates have been (re)created, similar to what https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion does?

**Comment by almereyda** [comment]
The above implies that service discovery via `/etc/hosts` or local DNS exists that maps the desired hostnames to locally accessible IPs.

**Comment by anderspitman** [comment]
I believe this may be fixed in the latest release, as boringproxy now supports plain HTTP. Please let me know if this is not the case.
