### ISSUE TITLE
Serious Bug: "Unable to register TCP Forward"

### ISSUE THREAD

**Issue by LukeSchoen** [boringproxy/boringproxy#39]
The rest of the message.. "ssh: tcpip-forward request denied by user"

We think what causes it is when the client crashes without properly killing the tunnels, so the server leaves them open and you can't open new ones.

It's possible to work around this by running killall sshd on the server machine. Note this solution is obviously NOT great and either difficult or impossible for users to do on the demo site.

Boring Proxy's really really really good but this issue is kind of a massive deal breaker.

I'm pledging 10$ US to get this fixed! (send your btc / paypal wallet address to dacoolies at gmail.com once it's fixed for reward)

Thank you anderspit!

**Comment by anderspitman** [comment]
Thanks for the report @LukeSchoen. I'm aware of the issue and tracking it in #23. I haven't looked too deeply into a fix yet since newer versions of the client are much more stable for me personally.

I'm curious, do the ports eventually open back up on the server if you wait long enough, or is the tunnel completely useless after that point (ie have to delete and recreate it to get a new random port)?

Do keep in mind that the demo server is only intended for people to give boringproxy a try, not for production uses. It's likely that if boringproxy ever gets popular that people will start abusing it for phishing attacks and who knows what else. In that case I'll just shut it down, so you shouldn't rely on it.

**Comment by LukeSchoen** [comment]
Thank you Anders!

Yes the ports do eventually reopen by themselves (sometimes it takes several hours tho)

I'de be very happy to try the new more stable version of the client, where is the best place to get that btw?

I've been using the demo for some small scale production use (just a handful of clients a month connecting to my login server to let them use my software) i would be very happy to consider a more permanent solution but BP is my first foray into servers & proxyies so really don't know where to look / start exactly.

For my needs (< 1mb a week) the demo server does a great job! im really hoping no one tried to abuse / destroy the system!

That 10$ of btc or cash is still waiting if you do get a minute to fix it, looking forward to hearning more Thanks again my dude!

**Comment by anderspitman** [comment]
Interesting. Honestly the stability on any of the last few official [releases](https://github.com/boringproxy/boringproxy/releases) has been quite good for me. Can you give any more details about the circumstances under which the client crashes? Does it completely fail or just freeze and stop working? Is there anything printed to the console?

If your load is that light, you might be better off with something more production ready like ngrok. They also have a free tier. Though I am curious does boringproxy offer any advantages for you over ngrok? Obviously I prefer it otherwise I wouldn't have made it but I like to know what features people like and use.

You might also check my list of tunnel proxies if you haven't seen it yet: https://github.com/anderspitman/awesome-tunneling

And thanks for the $ offer. I will eventually have donation options once boringproxy is out of beta, but it'll probably be a few months out.

**Comment by anderspitman** [comment]
@LukeSchoen can you try one thing for me: if you delete the tunnel and recreate it, can the client connect after that? I believe the problem is the sshd server is holding on to ports when they don't get closed properly (more likely if the client crashes). If that is the case, simply switching to a new port (by making a new tunnel which will give you a new random port) should work.

If that fixes it, I can add a option to the UI to switch to a new port without having to completely recreate it.

**Comment by LukeSchoen** [comment]
Hey man,

Yeah that absoutely does fix the issue, however it's not such a good solution since the port is part of the external connection resolution, which is to say changing ports is as bad as changing address as any external programs referencing that connection will no longer connect / work.

I'm something of a c++ guy myself and I've got pretty experience with sockets etc, is there somewhere i cool look if i wanted to give you a hand?

Thanks for makign this a priority as i say everything else about boring proxy is exactly how i would like it to be!

**Comment by LukeSchoen** [comment]
Hey sorry i must have missed your previous message!

I'll download the new client program right now!, the crashes are mostly caused by me accidentilly unplugging the computer! but as i say one time that was not the case (i belive no extra info was printed that i noticed)

I will check out ngrok if neccisary but honestly i love BP, the interface is sleak and it just works so well! is it the only proxy I've tried thusfar and I'm %100 satisfied! Making a donation system is a good idea i'm sure im not the only one who loves BP. You should definitely consider making a permanant proxy like the demo server always available (maybe with some $ charge)

Thanks again for you great work and effort! looking forward to solving this final key bug.

**Comment by anderspitman** [comment]
You bring up a good point. For normal tunnels changing the port isn't a problem, because it's behind a domain name anyway. But if someone is forwarding a TCP connection then you need to be able to keep the port. However, I'm not sure there's a solid solution. Half-open TCP sockets are a common problem. I'll look into it more deeply though. There might be a timeout or something on the server that I can set to be more aggressive.

**Comment by LukeSchoen** [comment]
Excellent it sounds like you already have a good solution to the problem, a 5 minute cool down would be perfect fine.

I'm no expert but my understanding of TCP connection accepting is that the server can allow for multiple connections and accept or reject each one as it sees fit, would it be possible to have the server keep a thread open which waits for additional connections (even if one has previously been accepted) and then simply drop any previously open (or half open) connections to always prefer the most recent connection request?

Thanks again having a direct like to BP's designer is one of the reasons i love using this system!

**Comment by anderspitman** [comment]
It may be possible to do that. I know with normal TCP listeners you can set `SO_REUSEADDR`. But I'm not sure that's quite the same problem we're having here. Between the HTTP server, the SSH server, and the SSH client there are a lot of TCP ports being opened in the system, so it's a bit complicated.

**Comment by LukeSchoen** [comment]
yes Indeed that does sound a bit complex, still i have great hopes you have shown excellent coding knowledge im sure you have the skills to boot!

Based on the original message "SSH: tcpip-forward request denied by user" im guessing it's the SSH serving part of the code which is causing todays issue, again I'de love to get involved! if there's any cpp involved im your man (admitidly as of yet i know almost nothing about go) maybe if we tested with SSH disabled (skipping token checks etc) we could narrow down the where exactly the open socket lies, looking forward to hearing more, thanks again!

**Comment by anderspitman** [comment]
@LukeSchoen I think there's a reasonable good chance the solution here will solve the problem: https://serverfault.com/a/595335/549753

I've set the demo server where it should timeout after ~30 seconds if the client disconnects unexpectedly. Can you give it a shot and let me know?

**Comment by LukeSchoen** [comment]
@anderspitman VERY NICE DUDE!

Everything it working nicely on my end, I'll trigger the issue now and let you know if the problem comes up and or doesnt resolve itself within about 30 seconds.

Thanks again! my man!

**Comment by LukeSchoen** [comment]
Excellent work !

I just pull the power and by the time the computer had restarted the ports were open and useable again!

I owe ya 10 bucks and a whole lot of thanks! Great stuff.

**Comment by anderspitman** [comment]
Your poor computer haha.

We'll call it even since you helped me track down one of the biggest known bugs and the solution ended up being an easy fix.

Let me know if it crops up again.

Thanks!

**Comment by LukeSchoen** [comment]
Sounds Good Will Do Thanks dude!
