### ISSUE TITLE
Error starting boringproxy server: apparent syntax error

### ISSUE THREAD

**Issue by Zygodon** [boringproxy/boringproxy#44]
Hi @anderspitman , I get error messages on starting the server:

pi@raspberrypi:~ $ sudo ./boringproxy server
./boringproxy: 1: ./boringproxy: �F@p@8: not found
./boringproxy: 2: ./boringproxy: @@@@@00��@�@��@�@dd@@0�R0�RS���pF�pF���ـ�: not found
./boringproxy: 2: ./boringproxy: @: not found
./boringproxy: 1: ./boringproxy: ELF: not found
./boringproxy: 3: ./boringproxy: Syntax error: word unexpected (expecting ")")
pi@raspberrypi:~ $ 

Any comment?

**Comment by anderspitman** [comment]
Hi @Zygodon. Most likely you downloaded the `-amd64` image file instead of the `-arm64` file. You're not the first person to run into this problem. I've been using the default architecture names of the golang compiler because it's convenient, but I think I'm going to switch to x64 or x86_64 in the future.
