### ISSUE TITLE
Accessing bridged services

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy#6]
In following up from the blind experiment #5, I have set up a tunnel with:

- test.outpost.test.io domain
- 10.10.10.10 client address
- 8080 client port
- Any client

This is the connection that had been created for me:

> test.outpost.test.io:38281 -> any -> 10.10.10.10:8080 

When trying to access https://test.outpost.test.io/, I am displayed with

    Get "http://localhost:38281/": dial tcp 127.0.0.1:38281: connect: connection refused

After doint that, it is not evident to me

- what the offered private key is used for,
- why a random port has been selected to be forwarded,
- and how to connect to the forwarded service.

The firewall for port 8080 is open on the target client machine.  
The service listens on all interfaces 0.0.0.0.

Also trying to access https://test.outpost.test.io:38281 fails.

```
root@outpost:~/boringproxy# ss -natp | grep boringproxy
LISTEN 0      128                             *:80                            *:*                     users:(("boringproxy",pid=16256,fd=9))
LISTEN 0      128                             *:443                           *:*                     users:(("boringproxy",pid=16256,fd=8))
ESTAB  0      92       [::ffff:148.251.175.151]:443      [::ffff:80.187.118.30]:26887                 users:(("boringproxy",pid=16256,fd=10))
```

Thank you for this fresh approach in connection layering, and I'd like to continue to help with testing and feedback.

Yet what am I missing up until now?

**Comment by almereyda** [comment]
The same error appears with the test instance at bpdemo.brng.pro:

    Get "http://localhost:38275/": dial tcp 127.0.0.1:38275: connect: connection refused

An interesting detail my test instance is also, that the daemon is not even listening on the expected port:

```
root@outpost:~/boringproxy# ss -tlnp | grep boring
LISTEN    0         128                      *:80                     *:*        users:(("boringproxy",pid=23571,fd=8))
LISTEN    0         128                      *:443                    *:*        users:(("boringproxy",pid=23571,fd=7))
root@outpost:~/boringproxy# 
```

Maybe I'm expecting too much from this pre-release, and should await further commits first.

**Comment by anderspitman** [comment]
@almereyda, thanks for your testing! This is exactly the sort of feedback I need to get boringproxy to 1.0. This is the part of the process where I start to realize the assumptions I've made and how confusing a lot of the details are to those who haven't been breathing this for the past month.

The core problem here is that leaving client set to "Any" will result in no automation. "Any" is a poor name. It should probably be "None". Basically it means you have to connect the tunnel manually using an SSH client. It also means the client port and client address from the web UI have no affect, since those are controlled by the client.

In you example case above, you would download the private key to `id_rsa`, then run:

```bash
ssh -NR 127.0.0.1:38281:10.10.10.10:8080 test.outpost.test.io
```

See the [tunnel.sh](https://github.com/boringproxy/boringproxy/blob/ada81bae62ca18f8b3e004a97c03d0f1d6d24431/tunnel.sh) file for a script that automates this.


A few other details:

* If you want to bind directly to 38281 on the server (ie for raw TCP tunnels without TLS), you need to check the "Allow External TCP" box.
* The reason you don't see the daemon listed is because there is it doesn't bind the port until you create the SSH tunnel.

**Comment by almereyda** [comment]
Okay, the SSH thing and what happens behind the curtains is still a thing I need to figure out myself.

Closing, as this isn't an issue with the code base itself, and we have kept sufficient details from this conversation here for public, not advanced usage, in https://github.com/boringproxy/boringproxy.io/pull/2 and #7.
