### ISSUE TITLE
If no username is specified when running client, use owner of token

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#66]

**Comment by anderspitman** [comment]
So I don't forget this time, the problem is that the API is designed such that the path of the request is `/users/<username>/client`, so the client has to know the username before hand. We could either add an endpoint to use the token to figure out what the user is, or change the API to not require knowing the user on the client.

**Comment by almereyda** [comment]
How does it work when logging in via the frontend, doesn't it use the API
from a "fat" JavaScript client as well, but is instead a non-JavaScript
application that is rendered on the server, and talks to it directly
through its own, separate endpoints?

**Comment by anderspitman** [comment]
@almereyda sorry I missed this comment before. The frontend doesn't have any JavaScript, but also up until today there was no way to add clients from the web UI. See #141.

**Comment by WGrobler** [comment]
I see you changed it so that username is no longer required to connect. This makes is easier to set up and could be the default since it actually makes client setup easier, but it does lower the authentication strength since you no longer require both the username & token to be an authentication pair. 

Since the token has sufficient strength against brute force attacks, I don't think we need an authentication pair and we can go on token alone (token alone is the default way to connect to web UI anyway), but I wanted to raise the point anyway before changes are permanent.

**Comment by WGrobler** [comment]
I agree with @anderspitman, token should be strong enough and not needing to provide it makes the client setup easier.

**Comment by anderspitman** [comment]
Fixed in v0.9.0.
