### ISSUE TITLE
When user creates entry with "https" in admin UI, delete function checks / unchecks box instead of deleting

### ISSUE THREAD

**Issue by lightnin** [boringproxy/boringproxy#68]
When user incorrectly enters "https" at the start of URL field in "AddTunnel" page of admin interface, the interface gets into a state shown in screenshot in which pressing "delete" on the created tunnel does not delete the tunnel, but only checks or unchecks a checkbox. 

<img width="919" alt="Screenshot 2021-02-18 at 08 47 58" src="https://user-images.githubusercontent.com/1538027/108322739-200b3200-71c6-11eb-8828-35386aad8f50.png">

Firefox 85.0.2 (64-bit) on a Mac.

**Comment by lightnin** [comment]
Once in this state, tried logging into admin interface with Chrome Version 88.0.4324.150 (Official Build) (x86_64) and same issue occurs.

**Comment by lightnin** [comment]
Workaround is to delete boringproxy_db.json, which will be recreated next time you run boringproxy.

**Comment by anderspitman** [comment]
Well that's bizarre.

**Comment by anderspitman** [comment]
@lightnin I'm not even able to create a tunnel starting with `https://`. It fails to get the cert every time, as it should since the domain is passed directly into certmagic which I'm pretty sure only accepts naked domains. I feel like there must be something else going on here.

That said, we could potentially do a check to check if the domain starts with `http` and tell the user in that case.

**Comment by lightnin** [comment]
Sounds like a good fix! I think when I made this entry TLS termination was either on client or maybe pass through, in case that matters.
