### ISSUE TITLE
UDP supported?

### ISSUE THREAD

**Issue by mrbluecoat** [boringproxy/boringproxy#85]
Does boringproxy support UDP? For example, proxying clients attempting to access an IKEv2 VPN server behind NAT

**Comment by mrbluecoat** [comment]
As a follow-up question, you mention on https://github.com/anderspitman/awesome-tunneling `[boringproxy] solves almost everything I want except auto DNS management, and that's planned `. What are your plans for supporting DNS (UDP port 53) and timeline? Perhaps the ability to do ad and content blocking, like pi-hole?

**Comment by anderspitman** [comment]
Hi @mrbluecoat. Unfortunately boringproxy doesn't support UDP, since we depend on SSH which is TCP-based. I don't currently have any plans to change this. I'd recommend finding another solution on the list.

The DNS support mentioned refers to managing DNS records, not implementing the DNS protocol itself. So for example it would be nice if you could create a tunnel in boringproxy, and it could use a Namecheap/Cloudflare/AWS/etc API key to update your DNS records for the tunnel.

**Comment by mrbluecoat** [comment]
socat and https://github.com/ambrop72/badvpn#peer-to-peer-vpn come to mind.. Any other recommendations for a transparent, performant proxy?
