### ISSUE TITLE
Not working for Docker services

### ISSUE THREAD

**Issue by luke2m** [boringproxy/boringproxy#86]
This is probably user error somewhere, but I have some services running directly on my home server and some running on Docker. The services running directly work perfectly, but when you go to the url for services in Docker, it  says,
```  Get "http://localhost:33207/": dial tcp 127.0.0.1:33207: connect: connection refused```

The client log says 
```Jun 01 21:16:00 cloud boringproxy[3330116]: 2021/06/01 21:16:00 BoreTunnel error:  Failed to dial: %!(EXTRA *errors.errorString=ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)```
The server log is completely normal. What is going on?

**Comment by almereyda** [comment]
Did you make sure to export your docker container ports to the host? I am using a similar configuration, and bind those ports on the `lo` interface, from where they can be reached at `127.0.0.1` soley for the proxy. Alternatively, I guess, you would need to forward to the respective container's Docker IP [¹](https://stackoverflow.com/questions/17157721/how-to-get-a-docker-containers-ip-address-from-the-host) directly, in order to reach one of its exposed ports. Some DNS-based service discovery could also automate the process for multiple services accessible in local, non-publicly routing network segments.

**Comment by luke2m** [comment]
The ports are exported: I can access it from the lan. Both 127.0.0.1 and 172.19.0.3 (docker ip) do not work.

**Comment by anderspitman** [comment]
That error tickles my memory, but I'm not sure. Have you tried ngrok, just to confirm that your setup should work assuming boringproxy is working correctly?

**Comment by anderspitman** [comment]
In that case I'm not sure what the problem might be, since docker appears to be working for @almereyda.

**Comment by almereyda** [comment]
Yes, it does here.
