### ISSUE TITLE
How to remove, uninstall or cleanup server

### ISSUE THREAD

**Issue by 1cgonza** [boringproxy/boringproxy#88]
Hi, 

I wanted to use this on my server in which I have a few running applications with nginx. Then realized that boringproxy can't get the certificates and the admin site redirects to a running application I have, probably it is using the same port as boringproxy.

On one side, my question is: can I run boringproxy on a server already running nginx?
If not, I don't really know what happened internally when I did `./boringproxy-linux-x86_64 server` and would like to know if there is a script that can uninstall it. If there is not something such as `./boringproxy-linux-x86_64 uninstall`, any hints as to what I need to do to cleanup?

Thanks!

**Comment by anderspitman** [comment]
Hey @1cgonza.

boringproxy isn't intended to be run alongside another reverse proxy like nginx. There's a good chance you'll run into a lot of issues trying to get that to work. Is there a reason you can't use boringproxy instead of nginx? It doesn't have as many features, but it should be sufficient for many reverse proxy needs.

As for uninstalling, I don't believe the current release writes any files other than the working directory (where you run it from). I've done some experiments with using XDG directories ($HOME/.config/boringproxy, $HOME/.local/share/boringproxy, etc) so maybe check if those exist. Future releases will probably be distributed as zipped directories that are guaranteed to never write outside, similar to how Zoom is packaged for Linux.

**Comment by 1cgonza** [comment]
@anderspitman thanks! good to know it did not write stuff somewhere else. As for replacing nginx with boringproxy I feel tempted but fear that some granular nginx configurations I currently have for certain apps might bite me in the ass if I move them into another proxy. 

Sorry to use this space to ask this kind of questions and feel free to close this issue, but if I just want to tunnel requests from a single domain I have in my ubuntu (nginx) server to my local machine running jellyfin, do you have any recommendation? I really wanted to try out boringproxy for its elegant simplicity, but can't commit to it entirely at the moment, maybe there is another option I can consider? I am a developer so I feel comfortable with a more developer oriented solution if you know of any :)

Awesome job by the way.

Cheers!

**Comment by anderspitman** [comment]
Hey @1cgonza. Sorry for the very late response. My current recommendation for most people is Cloudflare Tunnel. They made it free a few months ago, and it's by a large and reputable company.
